# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
